# Starter pipeline
- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'Test1'
    testType: 'app'
    monitorWhen: 'true'
    failOnIssues: true
# A list of tasty fruits
- Apple
- Orange
- Strawberry
- Mango
